### ISSUE TITLE
Common use case for review meeting

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#3]
Find a user story linking WP2, 3, 4 and 5 with a use case and demos wherever possible. We should make very clear the link between the science and the technologies we are implementing.
Suggestion to have a dedicated session in the [review meeting](https://indico.desy.de/event/28590/) for this.

**Comment by servansod** [comment]
Storyboard to be drafted (from PEB notes):
- PaN portal deployed at a NRI with access to data using the search API
- Pipeline developed by partner A running on partner B infrastructure
- Use of PaN-learning to access a NRI tutorial

**Comment by trudevonrichthoten** [comment]
My suggestion would be to split the process of the Demo into three main topics:

## Story Workflow

### The (FAIR) story. 
The story (implicitly) refers to the FAIR principles. It is what a generic scientist wants to achieve, like verifying a publication, 
improving the work of a publication by adding more data or applying the algorithm of
a publication to his/her own data.  
There are two reasons to start with a story and not a Use-Case.
- Stories can be easier matched to the FAIR principles, as they are very high level too.
- Stories can be easier digested by people not from this particular field (reviewers) as  they can be  matched to other fields too.

### The science use case.
Here we get more specific. So we describe the actual science and apply the story to that particular story. So there
could be more use cases associated to one story (FAIR case) We have about 10 reference datasets, so that should give us some concrete use cases.

### The ExPaNDS implementation.
Here we describe what you need to make the use case work in  a more efficient way by applying our great work of the previous 18 month or anticipatively  at the end of project. This is were we use a search either directly at a site with our search apI, we describe our envisioned pipelines and we can refer to the fact that if the PaN portal would exist, life would be so much easer. This part has to refer to work done in the different WP's
 
## Example I :

### Verify a publication (e.g. as a reviewer)

#### Story:  (Simple one to make my point)
Verify a publication (e.g. as a reviewer)
#### Use case:
Can be any PaN application.
####  ExPaNDS function:
You log into the PaN portal at EOSC; you select the data from the DOI of the paper;  you find a  infrastructure you have access to; you move the data to that infrastructure; you get the container (following the Software DOI) and the container registry and you run the container at the selected infrastructure with selected data. (Search API not needed)


## Example I I:

### Use existing data with new algorithms to improve the result of a publication
#### Story:  
Use existing data with new algorithms to improve the result of a publication This means almost all of FAIR is required.  (In Astro physics that would be e.g. re-intepreting the position of stars after knowing about the gravitational lens effect.)

#### Use case: Protein crystallographic 
As an example we take the pdb-redo activity. With existing data they found updated and optimised  crystallographic structures. They didn't even  use the raw data but only the MTZ data files. 

####  ExPaNDS Application:
Could  ExPaNDS have simplified that work? e.g. by making more data available or easier to access? We could have made the server pipeline available, in a standard fashion.

## More Examples

####   Story: Using all existing data from a particular field to verify the efficiency of a new algorithm!
You worked on a new algorithm in a field  (like Ptychography here at DESY) and you would like to show its efficienc before yiu apply for beamtime. So you go to OpenAire and find similar data which  could be handled by your pipeline. And you  run the algorithm over all the data you find from the same area.

**Comment by andygotz** [comment]
For the PDB-redo example we (ExPaNDS+PaNOSC) could go one step further and provide the raw data via the PDB. This way we contribute to improving the situation by implementing FAIR as recommended by the IUCr. 

We have a created a use case for this here: https://www.panosc.eu/use-cases/panosc-use-case-10-linking-raw-data-to-the-protein-data-bank-in-europe-pdbe/

**Comment by servansod** [comment]
## Demonstration for the ExPaNDS review 
_Following review preparation meeting from 2021-02-23_
1. Finding data (what data do we have?)
• You log into the PaN portal at EOSC (using PaN API) or
• DOI from a paper or
• Search facility at an EOSC Portal (B2Find or OpenAire) 
2. Finding resources
• Go to EGI and find a infrastructure you have access to; 
3. Prepare to Analyse (use case can be ‘notebookable’ and/or desktop, preferably both)
• you move the data to that infrastructure; 
• you get the container (following the Software DOI or find it at the PaN Software catalogue) and the container registry and (can the software come from 3rd site?)
4. you run the container at the selected infrastructure with selected data (Search API not needed)

## Follow-up
- [ ] Check what data is harvested for demo of data found through OpenAIRE (1.3) - Alun
- [ ] Check PaN search API is compatible with minimum metadata asked by the OAI-PMH standard - Alun
- [ ] Find a dataset from facility A (PSI?) compatible with analysis on remote desktop from facility B - Alun, Anton
- [ ] Find a dataset from facility C compatible with notebook-based analysis from facility D (HZDR?) - Alun, Anton
- [ ] Check with Giuseppe (EGI) for point 2 (infrastructure access) - Patrick
- [ ] Check for NeXus containerised data reduction - Uwe
- [ ] Link this implementation to a FAIR story and scientific use case (see [previous comment from Patrick](https://github.com/ExPaNDS-eu/ExPaNDS/issues/3#issuecomment-783285876)) - Alun, Anton
- [x] Prepare a draft Indico event - Sophie: https://indico.desy.de/event/28590/

## Resources
- [Example OAI-PMH record (see embedded code)](http://www.openarchives.org/OAI/openarchivesprotocol.html#Record)
- [Minimum metadata set for OAI-PMH](http://www.openarchives.org/OAI/2.0/oai_dc.xsd) - based on Dublin Core, there a lots of possibilities for additional 'optional' metadata.

**Comment by trudevonrichthoten** [comment]
I talked to Micheal S. The workflow we discussed yesterday, where we fetch code from the PaN software catalogue, create a container and push it into a registry is essentially done at DESY. The registry is gitlab itself and according to Michael, this registry is available from outside. So the created container can be fetched from any other facility build or pipeline system.

**Comment by antonbarty** [comment]
Example cases dug up from WP4 that don't quite solve problem:
1) Chris Reynolds has a recording of using JupyterHub as a demo.  We decided (with Patrick) that this fruit was a bit too low hanging to make a convincing demonstration.
Taking software from facility A to facility B
2) Diamond run things in containers for load management, but the software is pulled from a shared drive.  That means the software is not portable elsewhere as easily as we would like
3) CrystFEL is in GitLab at DESY and we tried building a singularity container; however the SLURM API for submitting processing jobs did not work from within the container so while the GUI works, the processing doesn't.
4) There were examples of Jupyter notebooks from UKRI, MaxIV and HZDR. 

Of course this leaves open taking data from elsewhere (eg data from PSI --> Diamond) for processing where that software is installed.    We had thought it would be easier to take software to the data, and taking the data to the software is sort of the wrong way around for this picture.

**Comment by trudevonrichthofen** [comment]
This is the answer from EGI.EU on a 'provider' provisioning of container resources in a horizontal infrastructure.

You can also request to use the EGi Container Cloud service via the EGI Marketplace:

https://marketplace.egi.eu/12-compute
(You can find this category clicking on: Compute > Cloud Container Compute)

For your information, in the following picture it's outlined how EGI.eu is supporting scientific
communities and facilitate the resource allocation process:


![image](https://user-images.githubusercontent.com/13493683/109916293-a38f4d80-7cb3-11eb-8828-577073860972.png)

Steps:

1.) The customer submits via the EGI Marketplace, or contact us via other channels, a list of technical requirements from
supporting the research experiment.

2.) EGI.eu will use these requirements to identify providers of the EGI Federation that best fit the customer's needs.

3.) With the EoIs collected, EGI prepare:

A Service Level Agreement with the customer. This agreement includes the "services" that EGI will provide to the customer together
with the level of technical support, etc.
An Operational Level Agreement with all the providers interested to support the customer.
In case of any problems/violations, etc. the customer will contact EGI
4.) On a regular basis (6 months) EGI.eu will monitor the service provision of the providers supporting the customer to make sure that
     services are offered taking into account the agreed service level agreements, etc.
5.) Customer is also invited to provide feedback and suggestions for improving the agreement every 6 months/1 year.

Cheers, Giuseppe

**Comment by servansod** [comment]
A few notes/actions following the review meeting prep meeting on 9.3.2021:
- [x] send a foodle to choose a date for the rehearsal (actual review not planned yet)
- [ ] update the review meeting Indico following the remarks on the agenda (Sophie)
- progress on the implementation with Jupyter Notebooks was made within WP4, including with a clear science case
- progress with the Tess-like platform: Oliver already developed a local instance of the platform and started personalising it a bit.
- [ ] add a workflow in the platform for the HZDR Jupyter Notebook use case (the one using the reference dataset that is in the last WP4 deliverable) (Oliver via Uwe)
- HZDR is harvested by OpenAIRE, and thanks to the ICAT plug-in developed by Rolf (HZB), some other ICAT facilities (HZB, Diamond, ISIS, ALBA, Elettra) might/could also be
- [ ] Check with Rolf if HZB is harvested (Sylvie)
- :warning: OpenAIRE might not be the best solution for us (harvesting requirements e.g.) so we should also focus on B2FIND

**Comment by servansod** [comment]
FAIR story illustrated in the demonstration by Krisztian, Carlo, Rajmund & Oliver + link to the demo explained in Patrick's overall picture and WP3-4-5 presentations. :heavy_check_mark:
